language: cpp
os: linux
dist: trusty
sudo: false

branches:
  only:
    - master

cache:
  apt: true

addons:
  apt:
    packages: [libcppunit-dev, libxml2-dev]

git:
  submodules: false

before_install:
  - git submodule update --init --remote -- schemas
  - if [ "$TRAVIS_OS_NAME" = "osx" ]; then brew update         ; fi
  - if [ "$TRAVIS_OS_NAME" = "osx" ]; then brew install cppunit; fi

matrix:
  include:
    - os: linux
      dist: bionic
      compiler: gcc

    - os: linux
      dist: bionic
      compiler: clang

    - os: linux
      dist: xenial
      compiler: gcc

    - os: linux
      dist: xenial
      compiler: clang

    - os: osx
      osx_image: xcode11.2
      compiler: clang

script:
  - mkdir build
  - cd build
  - cmake -DCMAKE_BUILD_TYPE=Release -DCMAKE_VERBOSE_MAKEFILE=ON ..
  - cmake --build . --target all
